#!/bin/sh

# This script is called by i3 on startup.

# Increase key speed via a rate change
xset r rate 300 50
# Note that the order might affect how it works
# Swap escape and caps
# Map the caps lock key to super...
setxkbmap -layout us -variant altgr-intl # -option caps:super

# But when it is pressed only once, treat it as escape.
#killall xcape ; xcape -e 'Super_L=Escape'

setxkbmap -option caps:swapescape
